enum USERS_ACTION_TYPES {
  ADD_USER = 'ADD_USER',
  UPDATE_USERS_LIST = 'UPDATE_USERS_LIST',
  REMOVE_USER = 'REMOVE_USER',
  UPDATE_NEW_USER = 'UPDATE_NEW_USER',
}

export default USERS_ACTION_TYPES;
