enum POSTS_ACTION_TYPES {
  GET_POSTS = 'GET_POSTS',
  GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS',
  GET_POSTS_ERROR = 'GET_POSTS_ERROR',

  GET_USER_POSTS = 'GET_USER_POSTS',
  GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS',
  GET_USER_POSTS_ERROR = 'GET_USER_POSTS_ERROR',
}

export default POSTS_ACTION_TYPES;
